//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.PublishService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.primestone.com/infrastructure", ConfigurationName="PublishService.IPublisherService")]
    public interface IPublisherService {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.primestone.com/serviceBus) of message ServiceStatusRequest does not match the default value (http://www.primestone.com/infrastructure)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.primestone.com/serviceBus/IServiceInstrumentable/ServiceStatus", ReplyAction="http://www.primestone.com/serviceBus/IServiceInstrumentable/ServiceStatusResponse" +
            "")]
        WebService.PublishService.ServiceStatusResponse ServiceStatus(WebService.PublishService.ServiceStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.primestone.com/serviceBus/IServiceInstrumentable/ServiceStatus", ReplyAction="http://www.primestone.com/serviceBus/IServiceInstrumentable/ServiceStatusResponse" +
            "")]
        System.Threading.Tasks.Task<WebService.PublishService.ServiceStatusResponse> ServiceStatusAsync(WebService.PublishService.ServiceStatusRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.primestone.com/serviceBus) of message ClearStatusRequest does not match the default value (http://www.primestone.com/infrastructure)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.primestone.com/serviceBus/IServiceInstrumentable/ClearStatus", ReplyAction="http://www.primestone.com/serviceBus/IServiceInstrumentable/ClearStatusResponse")]
        WebService.PublishService.ClearStatusResponse ClearStatus(WebService.PublishService.ClearStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.primestone.com/serviceBus/IServiceInstrumentable/ClearStatus", ReplyAction="http://www.primestone.com/serviceBus/IServiceInstrumentable/ClearStatusResponse")]
        System.Threading.Tasks.Task<WebService.PublishService.ClearStatusResponse> ClearStatusAsync(WebService.PublishService.ClearStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.primestone.com/infrastructure/IPublisherService/OnNewReading", ReplyAction="http://www.primestone.com/infrastructure/IPublisherService/OnNewReadingResponse")]
        string[] OnNewReading(Primestone.ImportExport.Application.ImportExport.Main.PublisherService.ReadingDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.primestone.com/infrastructure/IPublisherService/OnNewReading", ReplyAction="http://www.primestone.com/infrastructure/IPublisherService/OnNewReadingResponse")]
        System.Threading.Tasks.Task<string[]> OnNewReadingAsync(Primestone.ImportExport.Application.ImportExport.Main.PublisherService.ReadingDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.primestone.com/infrastructure/IPublisherService/OnNewReadings", ReplyAction="http://www.primestone.com/infrastructure/IPublisherService/OnNewReadingsResponse")]
        string[] OnNewReadings(Primestone.ImportExport.Application.ImportExport.Main.PublisherService.ReadingDTO[] dto, int readingType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.primestone.com/infrastructure/IPublisherService/OnNewReadings", ReplyAction="http://www.primestone.com/infrastructure/IPublisherService/OnNewReadingsResponse")]
        System.Threading.Tasks.Task<string[]> OnNewReadingsAsync(Primestone.ImportExport.Application.ImportExport.Main.PublisherService.ReadingDTO[] dto, int readingType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.primestone.com/infrastructure/IPublisherService/OnNewReadingsJson", ReplyAction="http://www.primestone.com/infrastructure/IPublisherService/OnNewReadingsJsonRespo" +
            "nse")]
        string[] OnNewReadingsJson(string jsonReading, int readingType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.primestone.com/infrastructure/IPublisherService/OnNewReadingsJson", ReplyAction="http://www.primestone.com/infrastructure/IPublisherService/OnNewReadingsJsonRespo" +
            "nse")]
        System.Threading.Tasks.Task<string[]> OnNewReadingsJsonAsync(string jsonReading, int readingType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.primestone.com/infrastructure/IPublisherService/Subscribe", ReplyAction="http://www.primestone.com/infrastructure/IPublisherService/SubscribeResponse")]
        bool Subscribe(string url, int readingType, string bindingName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.primestone.com/infrastructure/IPublisherService/Subscribe", ReplyAction="http://www.primestone.com/infrastructure/IPublisherService/SubscribeResponse")]
        System.Threading.Tasks.Task<bool> SubscribeAsync(string url, int readingType, string bindingName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.primestone.com/infrastructure/IPublisherService/UnSubscribe", ReplyAction="http://www.primestone.com/infrastructure/IPublisherService/UnSubscribeResponse")]
        bool UnSubscribe(string url, int readingType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.primestone.com/infrastructure/IPublisherService/UnSubscribe", ReplyAction="http://www.primestone.com/infrastructure/IPublisherService/UnSubscribeResponse")]
        System.Threading.Tasks.Task<bool> UnSubscribeAsync(string url, int readingType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.primestone.com/infrastructure/IPublisherService/InitializePublisher", ReplyAction="http://www.primestone.com/infrastructure/IPublisherService/InitializePublisherRes" +
            "ponse")]
        void InitializePublisher();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.primestone.com/infrastructure/IPublisherService/InitializePublisher", ReplyAction="http://www.primestone.com/infrastructure/IPublisherService/InitializePublisherRes" +
            "ponse")]
        System.Threading.Tasks.Task InitializePublisherAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ServiceStatus", WrapperNamespace="http://www.primestone.com/serviceBus", IsWrapped=true)]
    public partial class ServiceStatusRequest {
        
        public ServiceStatusRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ServiceStatusResponse", WrapperNamespace="http://www.primestone.com/serviceBus", IsWrapped=true)]
    public partial class ServiceStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.primestone.com/serviceBus", Order=0)]
        public string ServiceStatusResult;
        
        public ServiceStatusResponse() {
        }
        
        public ServiceStatusResponse(string ServiceStatusResult) {
            this.ServiceStatusResult = ServiceStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ClearStatus", WrapperNamespace="http://www.primestone.com/serviceBus", IsWrapped=true)]
    public partial class ClearStatusRequest {
        
        public ClearStatusRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ClearStatusResponse", WrapperNamespace="http://www.primestone.com/serviceBus", IsWrapped=true)]
    public partial class ClearStatusResponse {
        
        public ClearStatusResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPublisherServiceChannel : WebService.PublishService.IPublisherService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PublisherServiceClient : System.ServiceModel.ClientBase<WebService.PublishService.IPublisherService>, WebService.PublishService.IPublisherService {
        
        public PublisherServiceClient() {
        }
        
        public PublisherServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PublisherServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublisherServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublisherServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.PublishService.ServiceStatusResponse WebService.PublishService.IPublisherService.ServiceStatus(WebService.PublishService.ServiceStatusRequest request) {
            return base.Channel.ServiceStatus(request);
        }
        
        public string ServiceStatus() {
            WebService.PublishService.ServiceStatusRequest inValue = new WebService.PublishService.ServiceStatusRequest();
            WebService.PublishService.ServiceStatusResponse retVal = ((WebService.PublishService.IPublisherService)(this)).ServiceStatus(inValue);
            return retVal.ServiceStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService.PublishService.ServiceStatusResponse> WebService.PublishService.IPublisherService.ServiceStatusAsync(WebService.PublishService.ServiceStatusRequest request) {
            return base.Channel.ServiceStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService.PublishService.ServiceStatusResponse> ServiceStatusAsync() {
            WebService.PublishService.ServiceStatusRequest inValue = new WebService.PublishService.ServiceStatusRequest();
            return ((WebService.PublishService.IPublisherService)(this)).ServiceStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.PublishService.ClearStatusResponse WebService.PublishService.IPublisherService.ClearStatus(WebService.PublishService.ClearStatusRequest request) {
            return base.Channel.ClearStatus(request);
        }
        
        public void ClearStatus() {
            WebService.PublishService.ClearStatusRequest inValue = new WebService.PublishService.ClearStatusRequest();
            WebService.PublishService.ClearStatusResponse retVal = ((WebService.PublishService.IPublisherService)(this)).ClearStatus(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService.PublishService.ClearStatusResponse> WebService.PublishService.IPublisherService.ClearStatusAsync(WebService.PublishService.ClearStatusRequest request) {
            return base.Channel.ClearStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService.PublishService.ClearStatusResponse> ClearStatusAsync() {
            WebService.PublishService.ClearStatusRequest inValue = new WebService.PublishService.ClearStatusRequest();
            return ((WebService.PublishService.IPublisherService)(this)).ClearStatusAsync(inValue);
        }
        
        public string[] OnNewReading(Primestone.ImportExport.Application.ImportExport.Main.PublisherService.ReadingDTO dto) {
            return base.Channel.OnNewReading(dto);
        }
        
        public System.Threading.Tasks.Task<string[]> OnNewReadingAsync(Primestone.ImportExport.Application.ImportExport.Main.PublisherService.ReadingDTO dto) {
            return base.Channel.OnNewReadingAsync(dto);
        }
        
        public string[] OnNewReadings(Primestone.ImportExport.Application.ImportExport.Main.PublisherService.ReadingDTO[] dto, int readingType) {
            return base.Channel.OnNewReadings(dto, readingType);
        }
        
        public System.Threading.Tasks.Task<string[]> OnNewReadingsAsync(Primestone.ImportExport.Application.ImportExport.Main.PublisherService.ReadingDTO[] dto, int readingType) {
            return base.Channel.OnNewReadingsAsync(dto, readingType);
        }
        
        public string[] OnNewReadingsJson(string jsonReading, int readingType) {
            return base.Channel.OnNewReadingsJson(jsonReading, readingType);
        }
        
        public System.Threading.Tasks.Task<string[]> OnNewReadingsJsonAsync(string jsonReading, int readingType) {
            return base.Channel.OnNewReadingsJsonAsync(jsonReading, readingType);
        }
        
        public bool Subscribe(string url, int readingType, string bindingName) {
            return base.Channel.Subscribe(url, readingType, bindingName);
        }
        
        public System.Threading.Tasks.Task<bool> SubscribeAsync(string url, int readingType, string bindingName) {
            return base.Channel.SubscribeAsync(url, readingType, bindingName);
        }
        
        public bool UnSubscribe(string url, int readingType) {
            return base.Channel.UnSubscribe(url, readingType);
        }
        
        public System.Threading.Tasks.Task<bool> UnSubscribeAsync(string url, int readingType) {
            return base.Channel.UnSubscribeAsync(url, readingType);
        }
        
        public void InitializePublisher() {
            base.Channel.InitializePublisher();
        }
        
        public System.Threading.Tasks.Task InitializePublisherAsync() {
            return base.Channel.InitializePublisherAsync();
        }
    }
}
