//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.primestone.com/serviceBus", ConfigurationName="ServiceReference1.IBusinessSubsProcess")]
    public interface IBusinessSubsProcess {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.primestone.com/serviceBus/IServiceInstrumentable/ServiceStatus", ReplyAction="http://www.primestone.com/serviceBus/IServiceInstrumentable/ServiceStatusResponse" +
            "")]
        string ServiceStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.primestone.com/serviceBus/IServiceInstrumentable/ServiceStatus", ReplyAction="http://www.primestone.com/serviceBus/IServiceInstrumentable/ServiceStatusResponse" +
            "")]
        System.Threading.Tasks.Task<string> ServiceStatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.primestone.com/serviceBus/IServiceInstrumentable/ClearStatus", ReplyAction="http://www.primestone.com/serviceBus/IServiceInstrumentable/ClearStatusResponse")]
        void ClearStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.primestone.com/serviceBus/IServiceInstrumentable/ClearStatus", ReplyAction="http://www.primestone.com/serviceBus/IServiceInstrumentable/ClearStatusResponse")]
        System.Threading.Tasks.Task ClearStatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.primestone.com/serviceBus/IBusinessSubsProcess/ProcessReadingJSON")]
        void ProcessReadingJSON(string jsonDTO);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.primestone.com/serviceBus/IBusinessSubsProcess/ProcessReadingJSON")]
        System.Threading.Tasks.Task ProcessReadingJSONAsync(string jsonDTO);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.primestone.com/serviceBus/IBusinessSubsProcess/ProcessReadingsJSON")]
        void ProcessReadingsJSON(string[] jsonDTO);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.primestone.com/serviceBus/IBusinessSubsProcess/ProcessReadingsJSON")]
        System.Threading.Tasks.Task ProcessReadingsJSONAsync(string[] jsonDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.primestone.com/serviceBus/IBusinessSubsProcess/Ping", ReplyAction="http://www.primestone.com/serviceBus/IBusinessSubsProcess/PingResponse")]
        void Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.primestone.com/serviceBus/IBusinessSubsProcess/Ping", ReplyAction="http://www.primestone.com/serviceBus/IBusinessSubsProcess/PingResponse")]
        System.Threading.Tasks.Task PingAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBusinessSubsProcessChannel : WebService.ServiceReference1.IBusinessSubsProcess, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BusinessSubsProcessClient : System.ServiceModel.ClientBase<WebService.ServiceReference1.IBusinessSubsProcess>, WebService.ServiceReference1.IBusinessSubsProcess {
        
        public BusinessSubsProcessClient() {
        }
        
        public BusinessSubsProcessClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BusinessSubsProcessClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessSubsProcessClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessSubsProcessClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ServiceStatus() {
            return base.Channel.ServiceStatus();
        }
        
        public System.Threading.Tasks.Task<string> ServiceStatusAsync() {
            return base.Channel.ServiceStatusAsync();
        }
        
        public void ClearStatus() {
            base.Channel.ClearStatus();
        }
        
        public System.Threading.Tasks.Task ClearStatusAsync() {
            return base.Channel.ClearStatusAsync();
        }
        
        public void ProcessReadingJSON(string jsonDTO) {
            base.Channel.ProcessReadingJSON(jsonDTO);
        }
        
        public System.Threading.Tasks.Task ProcessReadingJSONAsync(string jsonDTO) {
            return base.Channel.ProcessReadingJSONAsync(jsonDTO);
        }
        
        public void ProcessReadingsJSON(string[] jsonDTO) {
            base.Channel.ProcessReadingsJSON(jsonDTO);
        }
        
        public System.Threading.Tasks.Task ProcessReadingsJSONAsync(string[] jsonDTO) {
            return base.Channel.ProcessReadingsJSONAsync(jsonDTO);
        }
        
        public void Ping() {
            base.Channel.Ping();
        }
        
        public System.Threading.Tasks.Task PingAsync() {
            return base.Channel.PingAsync();
        }
    }
}
